version: "3"
services: 
    mongodb:
        image: mongo:4.2.5
        container_name: mongo
        ports: 
            - 27017:27017

    mongo-seed:
        build: ./DB
        container_name: mongo-seed
        links:
            - mongodb
    # app:
    #     container_name: iris
    #     build: ./
    #     volumes: 
    #         - ./:/usr/src/app
    #     stdin_open: true
    #     tty: true
    #     ports: 
    #         - 8080:8080